# image config
im_height: 227
im_width: 227
im_channel: 3

# pose config

# action config

# network config
epochs : 100
batch_size : 10
weight_decay : 1e-4
initial_learning_rate : 0.05
minimum_learning_rate : 0.0001

test_batch_size : 10

# dataset config
num : 400
train_num : 237
test_num : 42
label_smoothing : 0.1

